### ISSUE TITLE
Don't discard tiles when computing overlap

### ISSUE THREAD

**Issue by hinerm** [fiji/Stitching#10]
When compute overlap is checked, it seems that it is possible to just discard tiles if they are below some threshold for goodness of fit.

In the cases where we have solid stage positions from metadata, at least, it seems like there is no reason to just throw these tiles away. At the least, maybe there should be an option so the user can decide if they want poorly fitting tiles discarded or retained (because certainly there must always be a "best" fit position, even if it is below a threshold).

**Comment by ctrueden** [comment]
At the recent hackathon in Konstanz, @hoerldavid told me that his new ImgLib2-driven stitching code no longer suffers from this problem. In any case, I am closing this issue, since it is not a problem we will work on fixing in this particular repository. Rather, the solution will be an updated version of the stitching plugin which is more general/flexible/awesome.
